### ISSUE TITLE
SDK 48 Compatibility

### ISSUE THREAD

**Issue by PolyPlugins** [echowaves/expo-storage#2] opened 2023-03-13 06:19 UTC
Any plans to make compatible for the SDK 48? There's a pretty important bugfix for Samsung devices in there, but this package is preventing us from updating. The main issue appears to be with expo-file-system, if our app didn't make use of this library, it probably wouldn't be much of an issue, but forcing isn't really an option when building using expo. We did find updating expo, but leaving expo-file-system as 15.1.1 works in our testing, but we'd like our app to be up to date before releasing to production.

**Comment by dmitryame** [comment] 2023-03-13 12:51
Done, give it a try now, I have not done any regressions yet, but let me know if it works for you.

**Comment by dmitryame** [comment] 2023-03-13 20:30
The upgrade seems to work with expo 48. Closing for now.

**Closed as completed by dmitryame** 2023-03-13 20:30 UTC

**Comment by PolyPlugins** [comment] 2023-03-14 00:38
Awesome, it works, thank you.

**Comment by jsagar95** [comment] 2023-03-28 06:20
`expo-storage` causes app (with `SDK 48` ) to crash on iOS devices.

Configuration when the app crashed:
 
  ```
    "expo-storage": "^48.0.1",
    "expo": "~48.0.9",
    "expo-dev-client": "~2.1.6",
    "expo-device": "~5.2.1",
    "expo-image-picker": "~14.1.1",
    "expo-linking": "~4.0.1",
    "expo-notifications": "~0.18.1",
    "expo-status-bar": "~1.4.2",
    "fetch-retry": "^5.0.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.4",
    "react-native-device-info": "^10.4.0",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.26.0"
```

**Comment by dmitryame** [comment] 2023-03-29 02:29
Can you provide some additional evidence? It's really hard to believe this module causes the issue -- it's a very simple wrapper around expo-file-system. 
Can the issue be reliably reproduced? If yes, please let me know what are the steps? 
Can you also share code samples that cause the issue? Could it be some weird key name which would also cause the expo-file-system to choke?
One more thing to try out, have you blown the node_modules and  yarn.lock and then re-build all the dependencies?
Please let me know what else I can do to help. 
Thanks

**Comment by jsagar95** [comment] 2023-03-29 06:08
Hi @dmitryame ,

I was not able to reproduce the error. The crash was most likely caused by setting up push notifications during the `eas build` process. If it reoccurs, I will share an update on this thread.

Thanks.

**Comment by PolyPlugins** [comment] 2023-03-29 14:29
> I was not able to reproduce the error. The crash was most likely caused by setting up push notifications during the `eas build` process. If it reoccurs, I will share an update on this thread.
> 
> Thanks.

If you still have problems and you're using expo's notifications, you could try OneSignal expo

**Comment by jsagar95** [comment] 2023-03-30 16:08
> > I was not able to reproduce the error. The crash was most likely caused by setting up push notifications during the `eas build` process. If it reoccurs, I will share an update on this thread.
> > Thanks.
> 
> If you still have problems and you're using expo's notifications, you could try OneSignal expo

I went ahead with expo-notifications. An error in the config file caused the crash. 

Thanks!
